name: Build and publish package

on:
  schedule:
    - cron: "0 12 * * 5"
  workflow_dispatch:

jobs:
  build_publish:
    name: "Build"
    runs-on: codeberg-small
    steps:
      - name: Install deps
        run: apt-get update && apt-get install buildah ca-certificates -y

      - name: Build and push
        uses: https://codeberg.org/actions/buildah-simple@main
        with:
          tag: "docker.io/library/landsj/ephcom:latest"
          context: .
          push: true
          username: "landsj"
          password: ${{ secrets.DOCKERHUB }}
          registry: "docker.io"
